"different setting between different os
if has("win32") || has("win16")
    set rtp+=~/vimfiles/bundle/Vundle.vim/
    let path='~/vimfiles/bundle'
else 
    set rtp+=~/.vim/bundle/Vundle.vim
endif

set nocompatible
filetype off
syntax enable

" always show status line
set laststatus=2

" no swap file
set noswapfile

" turn on wildmenu
set wildmenu

" access system clipboard
set clipboard=unnamed

" search ignore case by default
set ic

" highlight search
set hls

" increment search
set is

" map leader to space
let mapleader=" "

" appearence 
set background=dark
set guifont=DejaVu_Sans_Mono:h10
set number

" indention
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" plugins
if has("win32") || has("win16")
    call vundle#begin(path)
else 
    call vundle#begin()
endif
"vundle
Plugin 'gmarik/Vundle.vim'
" color scheme
Plugin 'BusyBee'
Plugin 'altercation/vim-colors-solarized'
" status line
Plugin 'bling/vim-airline'
" show marks
Plugin 'kshenoy/vim-signature'
" multiple line edit
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tpope/vim-surround'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-fugitive'
Plugin 'kien/ctrlp.vim'
" smooth scroll when pressing ctrl+d or ctrl u
Plugin 'joeytwiddle/sexy_scroller.vim'
call vundle#end()

filetype plugin indent on

"============================================================
autocmd VimEnter FileType javascript noremap <buffer> <C-f> :call JsBeautify()<cr>
autocmd VimEnter FileType html noremap <buffer> <C-f>:call HtmlBeautify()<cr>
autocmd VimEnter FileType css noremap <buffer> <C-f>:call CSSBeautify()<cr>

"============================================================
" ctrlp settings
let g:ctrlp_working_path_mode=0  
let g:ctrlp_max_files=0
let g:ctrlp_max_height=20

" color scheme
colorscheme Busybee

" nerdtree
let g:nerdtree_tabs_open_on_gui_startup=0 

" press enter to insert new lines
nmap <S-Enter> O<Esc>
nmap <CR> o<Esc>


"============================================================
" Smart way to manage windows
nmap <leader>h <c-w>h
nmap <leader>j <c-w>j
nmap <leader>k <c-w>k
nmap <leader>l <c-w>l
nmap <leader>c <c-w>c
nmap <leader>H <c-w>H
nmap <leader>J <c-w>J
nmap <leader>K <c-w>K
nmap <leader>L <c-w>L
nmap <leader>o <c-w>o
nmap <leader>w <c-w>

" js code format
nmap <leader>f :call JsBeautify()<cr>

" nerdtree navigator toggle
nmap  <leader>nd :NERDTreeToggle<cr>

"cursor shape change in different mode in iterm2
if $TERM_PROGRAM =~ "iTerm"
    let &t_SI = "\<Esc>]50;CursorShape=1\x7" " Vertical bar in insert mode
    let &t_EI = "\<Esc>]50;CursorShape=0\x7" " Block in normal mode
elseif &term =~ "^xterm"
    let &t_SI .= "\<Esc>[5 q"
    let &t_EI .= "\<Esc>[2 q"
endif
